// backend/scripts/premium_shop_products.js
//
// Hand-curated premium products (10 per category × 7 categories = 70).
// Each product uses a `design_key` and a `configuration` JSONB so the
// frontend renderer can compose the visual from templates — no JSX
// is stored in the database.

export const PREMIUM_PRODUCTS = [
  // ════════════════ PROFILE_THEME (10) ════════════════
  {
    id: 'theme_premium_ramadan_night', name: 'Ramadan Night Theme',
    description: 'Deep emerald profile with crescent accent, gold ornaments, and warm lantern glow. Perfect for the holy month.',
    category: 'PROFILE_THEME', rarity: 'LEGENDARY', price: 2500,
    featured: true, limited: true, isNew: true, available: true,
    theme: 'ramadan', collectionLabel: 'Premium Profile Themes',
    designKey: 'ramadan_night', configuration: {
      palette: ['#0B1510', '#2E6644', '#65C77C', '#F5C56A'],
      ornaments: ['crescent', 'lantern', 'star'],
      headerStyle: 'ornate-emerald',
      cardSurface: '#0F1A14',
      accentColor: '#F5C56A',
      pattern: 'arabesque-emerald',
    },
  },
  {
    id: 'theme_premium_eid_celebration', name: 'Eid Celebration Theme',
    description: 'White and gold profile with festive borders, sparkle accents, and celebratory arch ornaments.',
    category: 'PROFILE_THEME', rarity: 'LEGENDARY', price: 2500,
    featured: true, isNew: true, available: true,
    theme: 'eid_fitr', collectionLabel: 'Premium Profile Themes',
    designKey: 'eid_celebration', configuration: {
      palette: ['#FFFFFF', '#F5C56A', '#F59E0B', '#E5E7EB'],
      ornaments: ['sparkle', 'arch', 'lantern'],
      headerStyle: 'festive-gold',
      cardSurface: '#FFFCF5',
      accentColor: '#F59E0B',
      pattern: 'festive-arches',
    },
  },
  {
    id: 'theme_premium_quranic_emerald', name: 'Quranic Emerald Theme',
    description: 'Emerald background inspired by the Mushaf, with illuminated margins and Quranic flourishes.',
    category: 'PROFILE_THEME', rarity: 'MYTHIC', price: 4500,
    featured: true, limited: true, available: true,
    theme: 'quran', collectionLabel: 'Premium Profile Themes',
    designKey: 'quranic_emerald', configuration: {
      palette: ['#0F1A14', '#2E6644', '#65C77C', '#F5C56A'],
      ornaments: ['mushaf', 'illumination', 'verse'],
      headerStyle: 'illuminated-mushaf',
      cardSurface: '#13241B',
      accentColor: '#F5C56A',
      pattern: 'illuminated-margin',
    },
  },
  {
    id: 'theme_premium_midnight_mosque', name: 'Midnight Mosque Theme',
    description: 'Dark blue profile with mosque silhouette, twinkling stars, and crescent moon accent.',
    category: 'PROFILE_THEME', rarity: 'EPIC', price: 1500,
    available: true,
    theme: 'kaaba', collectionLabel: 'Premium Profile Themes',
    designKey: 'midnight_mosque', configuration: {
      palette: ['#0D1B2A', '#1B263B', '#F5C56A', '#E0E1DD'],
      ornaments: ['mosque-silhouette', 'star', 'crescent'],
      headerStyle: 'midnight-deep',
      cardSurface: '#102841',
      accentColor: '#F5C56A',
      pattern: 'starfield',
    },
  },
  {
    id: 'theme_premium_golden_heritage', name: 'Golden Heritage Theme',
    description: 'Black and gold profile with arabesque borders, regal accents, and Islamic heritage ornaments.',
    category: 'PROFILE_THEME', rarity: 'LEGENDARY', price: 3000,
    available: true,
    theme: 'kaaba', collectionLabel: 'Premium Profile Themes',
    designKey: 'golden_heritage', configuration: {
      palette: ['#000000', '#F5C56A', '#F59E0B', '#1A1A1A'],
      ornaments: ['arabesque', 'royal-crest', 'heritage'],
      headerStyle: 'royal-black-gold',
      cardSurface: '#0F0F0F',
      accentColor: '#F5C56A',
      pattern: 'arabesque-gold',
    },
  },
  {
    id: 'theme_premium_celestial', name: 'Celestial Theme',
    description: 'Cosmic gradient with twinkling stars, ethereal glow, and divine aura around the avatar.',
    category: 'PROFILE_THEME', rarity: 'MYTHIC', price: 5000,
    limited: true, available: true,
    theme: 'premium', collectionLabel: 'Premium Profile Themes',
    designKey: 'celestial', configuration: {
      palette: ['#0B0B3B', '#1A1A6E', '#E6E6FA', '#F5C56A'],
      ornaments: ['stars', 'divine-aura', 'celestial-glow'],
      headerStyle: 'cosmic-ethereal',
      cardSurface: '#0F0F50',
      accentColor: '#F5C56A',
      pattern: 'constellation',
    },
  },
  {
    id: 'theme_premium_minimal_islamic', name: 'Minimal Islamic Theme',
    description: 'Clean cream profile with subtle geometric accents — pure, elegant, professional.',
    category: 'PROFILE_THEME', rarity: 'RARE', price: 500,
    available: true,
    theme: 'geometry', collectionLabel: 'Premium Profile Themes',
    designKey: 'minimal_islamic', configuration: {
      palette: ['#F7FAF6', '#F5F9F4', '#2E6644', '#65C77C'],
      ornaments: ['minimal-geometric'],
      headerStyle: 'clean-cream',
      cardSurface: '#FFFFFF',
      accentColor: '#2E6644',
      pattern: 'minimal-lines',
    },
  },
  {
    id: 'theme_premium_andalusian', name: 'Andalusian Theme',
    description: 'Warm earth tones with arch-shaped frame, intricate Islamic patterns, and Moorish elegance.',
    category: 'PROFILE_THEME', rarity: 'EPIC', price: 1200,
    available: true,
    theme: 'geometry', collectionLabel: 'Premium Profile Themes',
    designKey: 'andalusian', configuration: {
      palette: ['#8B5A3C', '#D4A574', '#F5C56A', '#2E1810'],
      ornaments: ['horseshoe-arch', 'andalusian-pattern'],
      headerStyle: 'moorish-arch',
      cardSurface: '#F5E6D3',
      accentColor: '#8B5A3C',
      pattern: 'horseshoe-arches',
    },
  },
  {
    id: 'theme_premium_sacred_geometry', name: 'Sacred Geometry Theme',
    description: 'Emerald background with mandala patterns, sacred circles, and esoteric Islamic geometry.',
    category: 'PROFILE_THEME', rarity: 'EPIC', price: 1800,
    featured: true, available: true,
    theme: 'geometry', collectionLabel: 'Premium Profile Themes',
    designKey: 'sacred_geometry', configuration: {
      palette: ['#0F1A14', '#2E6644', '#65C77C', '#F5C56A'],
      ornaments: ['mandala', 'sacred-circle', 'geometric-star'],
      headerStyle: 'sacred-mandala',
      cardSurface: '#0E1810',
      accentColor: '#65C77C',
      pattern: 'mandala-emerald',
    },
  },
  {
    id: 'theme_premium_royal_emerald', name: 'Royal Emerald Theme',
    description: 'Deep emerald with golden crown motifs, regal borders, and premium ornate accents.',
    category: 'PROFILE_THEME', rarity: 'MYTHIC', price: 6000,
    limited: true, available: true,
    theme: 'premium', collectionLabel: 'Premium Profile Themes',
    designKey: 'royal_emerald', configuration: {
      palette: ['#0B1510', '#1B4D2E', '#65C77C', '#F5C56A'],
      ornaments: ['crown', 'royal-crest', 'emerald'],
      headerStyle: 'royal-emerald',
      cardSurface: '#0E1A12',
      accentColor: '#F5C56A',
      pattern: 'crown-emerald',
    },
  },

  // ════════════════ THEME / Name Effect (10) ════════════════
  {
    id: 'nameeffect_premium_golden_gradient', name: 'Golden Gradient',
    description: 'Username rendered with a luxurious gold gradient that flows from light to deep gold.',
    category: 'THEME', rarity: 'EPIC', price: 800, available: true,
    theme: 'premium', collectionLabel: 'Premium Name Effects',
    designKey: 'name_golden_gradient', configuration: {
      effect: 'gradient',
      gradient: ['#F5C56A', '#F59E0B', '#FFB300', '#F5C56A'],
      textShadow: '0 0 8px rgba(245, 197, 106, 0.4)',
      fontWeight: '800',
    },
  },
  {
    id: 'nameeffect_premium_emerald_glow', name: 'Emerald Glow',
    description: 'Elegant emerald text with a soft radiant glow that pulses with life.',
    category: 'THEME', rarity: 'EPIC', price: 800, available: true,
    theme: 'premium', collectionLabel: 'Premium Name Effects',
    designKey: 'name_emerald_glow', configuration: {
      effect: 'glow',
      color: '#65C77C',
      textShadow: '0 0 12px rgba(101, 199, 124, 0.6), 0 0 24px rgba(101, 199, 124, 0.4)',
      fontWeight: '700',
    },
  },
  {
    id: 'nameeffect_premium_crescent_shimmer', name: 'Crescent Shimmer',
    description: 'Crescent-themed animated shimmer effect across the username.',
    category: 'THEME', rarity: 'LEGENDARY', price: 1500,
    featured: true, isNew: true, available: true,
    theme: 'ramadan', collectionLabel: 'Premium Name Effects',
    designKey: 'name_crescent_shimmer', configuration: {
      effect: 'shimmer',
      color: '#F5C56A',
      accent: '#FFFFFF',
      textShadow: '0 0 14px rgba(245, 197, 106, 0.6)',
      animated: true,
    },
  },
  {
    id: 'nameeffect_premium_calligraphic', name: 'Calligraphic',
    description: 'Refined calligraphic typography inspired by classical Islamic manuscript style.',
    category: 'THEME', rarity: 'LEGENDARY', price: 1800,
    available: true,
    theme: 'quran', collectionLabel: 'Premium Name Effects',
    designKey: 'name_calligraphic', configuration: {
      effect: 'calligraphic',
      color: '#F5C56A',
      fontStyle: 'italic',
      letterSpacing: 1.2,
      fontWeight: '700',
    },
  },
  {
    id: 'nameeffect_premium_star_sparkle', name: 'Star Sparkle',
    description: 'Stars sparkle around the username in a celestial dance.',
    category: 'THEME', rarity: 'RARE', price: 500, available: true,
    theme: 'geometry', collectionLabel: 'Premium Name Effects',
    designKey: 'name_star_sparkle', configuration: {
      effect: 'sparkle',
      color: '#F5C56A',
      sparkleColor: '#FFFFFF',
      animated: true,
    },
  },
  {
    id: 'nameeffect_premium_royal_gold', name: 'Royal Gold',
    description: 'Bold, regal gold text with embossed depth and majestic presence.',
    category: 'THEME', rarity: 'EPIC', price: 1000, available: true,
    theme: 'premium', collectionLabel: 'Premium Name Effects',
    designKey: 'name_royal_gold', configuration: {
      effect: 'embossed',
      color: '#F5C56A',
      shadowColor: '#8B6914',
      fontWeight: '900',
      letterSpacing: 0.6,
    },
  },
  {
    id: 'nameeffect_premium_light_radiant', name: 'Light Radiant',
    description: 'Text emits soft rays of light that radiate from each character.',
    category: 'THEME', rarity: 'RARE', price: 600, available: true,
    theme: 'geometry', collectionLabel: 'Premium Name Effects',
    designKey: 'name_light_radiant', configuration: {
      effect: 'radiant',
      color: '#F5C56A',
      rays: true,
      textShadow: '0 0 6px #F5C56A, 0 0 12px #F5C56A',
    },
  },
  {
    id: 'nameeffect_premium_sacred_glow', name: 'Sacred Glow',
    description: 'Sacred gentle illumination around the username with subtle animation.',
    category: 'THEME', rarity: 'EPIC', price: 1200, available: true,
    theme: 'quran', collectionLabel: 'Premium Name Effects',
    designKey: 'name_sacred_glow', configuration: {
      effect: 'sacred-glow',
      color: '#65C77C',
      accent: '#F5C56A',
      glow: 'soft',
      animated: true,
    },
  },
  {
    id: 'nameeffect_premium_celestial_dawn', name: 'Celestial Dawn',
    description: 'Gradient from cyan to gold that evokes the first light of dawn.',
    category: 'THEME', rarity: 'MYTHIC', price: 2500,
    limited: true, available: true,
    theme: 'premium', collectionLabel: 'Premium Name Effects',
    designKey: 'name_celestial_dawn', configuration: {
      effect: 'gradient',
      gradient: ['#0EA5E9', '#E0E1DD', '#F5C56A'],
      textShadow: '0 0 10px rgba(245, 197, 106, 0.4)',
      fontWeight: '800',
    },
  },
  {
    id: 'nameeffect_premium_eternal_glow', name: 'Eternal Glow',
    description: 'Eternal cyan glow effect that never fades — for those who shine on.',
    category: 'THEME', rarity: 'LEGENDARY', price: 2000,
    available: true,
    theme: 'premium', collectionLabel: 'Premium Name Effects',
    designKey: 'name_eternal_glow', configuration: {
      effect: 'glow',
      color: '#0EA5E9',
      textShadow: '0 0 16px rgba(14, 165, 233, 0.7), 0 0 30px rgba(14, 165, 233, 0.5)',
      fontWeight: '700',
    },
  },

  // ════════════════ BACKGROUND (10) ════════════════
  {
    id: 'bg_premium_ramadan_lantern', name: 'Ramadan Lantern Background',
    description: 'Warm Ramadan nights with hanging lanterns, crescent moons, and soft starry backdrop.',
    category: 'BACKGROUND', rarity: 'EPIC', price: 1200,
    featured: true, isNew: true, available: true,
    theme: 'ramadan', collectionLabel: 'Premium Backgrounds',
    designKey: 'bg_ramadan_lantern', configuration: {
      layers: ['gradient', 'lanterns', 'stars', 'crescent'],
      palette: ['#0B1510', '#1B4D2E', '#2E6644', '#F5C56A'],
      pattern: 'lantern-field',
    },
  },
  {
    id: 'bg_premium_eid_celebration', name: 'Eid Celebration Background',
    description: 'Festive Eid background with confetti, ribbons, and golden sparkle bursts.',
    category: 'BACKGROUND', rarity: 'EPIC', price: 1200,
    isNew: true, available: true,
    theme: 'eid_fitr', collectionLabel: 'Premium Backgrounds',
    designKey: 'bg_eid_celebration', configuration: {
      layers: ['gradient', 'confetti', 'ribbons', 'sparkle'],
      palette: ['#FFFFFF', '#F5C56A', '#F59E0B'],
      pattern: 'festive-burst',
    },
  },
  {
    id: 'bg_premium_quran_mushaf', name: 'Mushaf Pages Background',
    description: 'Elegant Mushaf-inspired background with verses illuminated in margins.',
    category: 'BACKGROUND', rarity: 'LEGENDARY', price: 1800,
    available: true,
    theme: 'quran', collectionLabel: 'Premium Backgrounds',
    designKey: 'bg_quran_mushaf', configuration: {
      layers: ['gradient', 'mushaf-margins', 'verse-accents'],
      palette: ['#0F1A14', '#F5F9F4', '#2E6644', '#F5C56A'],
      pattern: 'illuminated-margin',
    },
  },
  {
    id: 'bg_premium_geometric_arabesque', name: 'Geometric Arabesque Background',
    description: 'Intricate arabesque patterns woven across the entire profile background.',
    category: 'BACKGROUND', rarity: 'LEGENDARY', price: 1500,
    available: true,
    theme: 'geometry', collectionLabel: 'Premium Backgrounds',
    designKey: 'bg_geometric_arabesque', configuration: {
      layers: ['gradient', 'arabesque-pattern', 'star-tiles'],
      palette: ['#0F1A14', '#2E6644', '#65C77C', '#F5C56A'],
      pattern: 'arabesque-emerald',
    },
  },
  {
    id: 'bg_premium_kaaba_night', name: 'Kaaba Night Background',
    description: 'The holy Kaaba at night under stars, with subtle silhouettes of pilgrims.',
    category: 'BACKGROUND', rarity: 'MYTHIC', price: 3500,
    limited: true, available: true,
    theme: 'kaaba', collectionLabel: 'Premium Backgrounds',
    designKey: 'bg_kaaba_night', configuration: {
      layers: ['gradient', 'kaaba-silhouette', 'star-field'],
      palette: ['#000000', '#1A1A1A', '#F5C56A', '#FFFFFF'],
      pattern: 'kaaba-night',
    },
  },
  {
    id: 'bg_premium_madinah_green', name: 'Madinah Green Dome Background',
    description: 'Inspired by the Green Dome of Madinah, with emerald gradients and crescent.',
    category: 'BACKGROUND', rarity: 'LEGENDARY', price: 2200,
    available: true,
    theme: 'madinah', collectionLabel: 'Premium Backgrounds',
    designKey: 'bg_madinah_green', configuration: {
      layers: ['gradient', 'green-dome', 'crescent', 'ornaments'],
      palette: ['#0F1A14', '#1B4D2E', '#2E6644', '#65C77C', '#F5C56A'],
      pattern: 'madinah-green',
    },
  },
  {
    id: 'bg_premium_celestial_stars', name: 'Celestial Stars Background',
    description: 'A deep blue cosmic sky with twinkling stars and ethereal light streaks.',
    category: 'BACKGROUND', rarity: 'EPIC', price: 1000,
    available: true,
    theme: 'geometry', collectionLabel: 'Premium Backgrounds',
    designKey: 'bg_celestial_stars', configuration: {
      layers: ['gradient', 'stars', 'light-streaks'],
      palette: ['#0B0B3B', '#1A1A6E', '#E6E6FA'],
      pattern: 'starfield',
    },
  },
  {
    id: 'bg_premium_desert_dunes', name: 'Desert Dunes Background',
    description: 'Warm desert sunset over dunes with horizon silhouette.',
    category: 'BACKGROUND', rarity: 'RARE', price: 600, available: true,
    theme: 'nature', collectionLabel: 'Premium Backgrounds',
    designKey: 'bg_desert_dunes', configuration: {
      layers: ['gradient', 'dunes', 'sunset'],
      palette: ['#F5C56A', '#F59E0B', '#8B5A3C', '#2E1810'],
      pattern: 'desert-dunes',
    },
  },
  {
    id: 'bg_premium_palm_garden', name: 'Palm Garden Background',
    description: 'Lush palm garden with stars peeking through fronds.',
    category: 'BACKGROUND', rarity: 'RARE', price: 500, available: true,
    theme: 'nature', collectionLabel: 'Premium Backgrounds',
    designKey: 'bg_palm_garden', configuration: {
      layers: ['gradient', 'palms', 'stars'],
      palette: ['#0F1A14', '#2E6644', '#65C77C', '#F5C56A'],
      pattern: 'palm-grove',
    },
  },
  {
    id: 'bg_premium_mosque_silhouette', name: 'Mosque Silhouette Background',
    description: 'Dramatic silhouette of a grand mosque against a golden sunset sky.',
    category: 'BACKGROUND', rarity: 'LEGENDARY', price: 1600,
    available: true,
    theme: 'kaaba', collectionLabel: 'Premium Backgrounds',
    designKey: 'bg_mosque_silhouette', configuration: {
      layers: ['gradient', 'mosque-silhouette', 'minarets'],
      palette: ['#F5C56A', '#F59E0B', '#1B263B', '#0D1B2A'],
      pattern: 'mosque-silhouette',
    },
  },

  // ════════════════ FRAME (10) ════════════════
  {
    id: 'frame_premium_ramadan_crescent', name: 'Ramadan Crescent Frame',
    description: 'Crescent moon frame with hanging lanterns at the corners — Ramadan vibes.',
    category: 'FRAME', rarity: 'EPIC', price: 1500,
    featured: true, isNew: true, available: true,
    theme: 'ramadan', collectionLabel: 'Premium Frames',
    designKey: 'frame_ramadan_crescent', configuration: {
      borderColor: '#F5C56A',
      backgroundColor: '#0B1510',
      ornaments: ['crescent', 'lantern'],
      thickness: 4,
      pattern: 'ramadan-frame',
    },
  },
  {
    id: 'frame_premium_eid_lantern', name: 'Eid Lantern Frame',
    description: 'Festive Eid frame shaped like hanging lanterns at each corner.',
    category: 'FRAME', rarity: 'EPIC', price: 1500,
    isNew: true, available: true,
    theme: 'eid_fitr', collectionLabel: 'Premium Frames',
    designKey: 'frame_eid_lantern', configuration: {
      borderColor: '#F59E0B',
      backgroundColor: '#FFFCF5',
      ornaments: ['lantern', 'sparkle'],
      thickness: 4,
      pattern: 'festive-lantern',
    },
  },
  {
    id: 'frame_premium_golden_arabesque', name: 'Golden Arabesque Frame',
    description: 'Intricate golden arabesque border with corner ornaments.',
    category: 'FRAME', rarity: 'LEGENDARY', price: 2000,
    available: true,
    theme: 'geometry', collectionLabel: 'Premium Frames',
    designKey: 'frame_golden_arabesque', configuration: {
      borderColor: '#F5C56A',
      backgroundColor: '#0F1A14',
      ornaments: ['arabesque'],
      thickness: 5,
      pattern: 'arabesque-gold',
    },
  },
  {
    id: 'frame_premium_geometric_star', name: 'Geometric Star Frame',
    description: 'Eight-pointed star pattern wrapping the avatar with elegant precision.',
    category: 'FRAME', rarity: 'EPIC', price: 1200, available: true,
    theme: 'geometry', collectionLabel: 'Premium Frames',
    designKey: 'frame_geometric_star', configuration: {
      borderColor: '#65C77C',
      backgroundColor: '#0F1A14',
      ornaments: ['geometric-star'],
      thickness: 4,
      pattern: 'geometric-star',
    },
  },
  {
    id: 'frame_premium_emerald_leaves', name: 'Emerald Leaves Frame',
    description: 'Delicate leaf ornaments around the avatar in emerald tones.',
    category: 'FRAME', rarity: 'RARE', price: 700, available: true,
    theme: 'nature', collectionLabel: 'Premium Frames',
    designKey: 'frame_emerald_leaves', configuration: {
      borderColor: '#2E6644',
      backgroundColor: '#F7FAF6',
      ornaments: ['leaf'],
      thickness: 3,
      pattern: 'leaves',
    },
  },
  {
    id: 'frame_premium_celestial_circle', name: 'Celestial Circle Frame',
    description: 'Cosmic circle with stars and cosmic rays radiating outward.',
    category: 'FRAME', rarity: 'MYTHIC', price: 3500,
    limited: true, available: true,
    theme: 'premium', collectionLabel: 'Premium Frames',
    designKey: 'frame_celestial_circle', configuration: {
      borderColor: '#0EA5E9',
      backgroundColor: '#0B0B3B',
      ornaments: ['celestial', 'star'],
      thickness: 5,
      pattern: 'celestial-circle',
    },
  },
  {
    id: 'frame_premium_minimal_islamic', name: 'Minimal Islamic Frame',
    description: 'Clean and elegant minimal frame with subtle geometric corner accent.',
    category: 'FRAME', rarity: 'COMMON', price: 200, available: true,
    theme: 'geometry', collectionLabel: 'Premium Frames',
    designKey: 'frame_minimal_islamic', configuration: {
      borderColor: '#2E6644',
      backgroundColor: '#FFFFFF',
      ornaments: ['minimal'],
      thickness: 2,
      pattern: 'minimal',
    },
  },
  {
    id: 'frame_premium_royal_gold', name: 'Royal Gold Frame',
    description: 'Ornate royal gold frame with crown motifs — fit for royalty.',
    category: 'FRAME', rarity: 'LEGENDARY', price: 2500,
    available: true,
    theme: 'premium', collectionLabel: 'Premium Frames',
    designKey: 'frame_royal_gold', configuration: {
      borderColor: '#F5C56A',
      backgroundColor: '#0F0F0F',
      ornaments: ['crown', 'royal'],
      thickness: 5,
      pattern: 'royal-frame',
    },
  },
  {
    id: 'frame_premium_crescent_glow', name: 'Crescent Glow Frame',
    description: 'A glowing crescent moon frame that pulses with celestial light.',
    category: 'FRAME', rarity: 'LEGENDARY', price: 2200,
    available: true,
    theme: 'ramadan', collectionLabel: 'Premium Frames',
    designKey: 'frame_crescent_glow', configuration: {
      borderColor: '#F5C56A',
      backgroundColor: '#0B1510',
      ornaments: ['crescent', 'glow'],
      thickness: 4,
      pattern: 'crescent-glow',
      glow: true,
    },
  },
  {
    id: 'frame_premium_mosque_arch', name: 'Mosque Arch Frame',
    description: 'Horseshoe arch frame inspired by grand mosque architecture.',
    category: 'FRAME', rarity: 'EPIC', price: 1400, available: true,
    theme: 'geometry', collectionLabel: 'Premium Frames',
    designKey: 'frame_mosque_arch', configuration: {
      borderColor: '#F5C56A',
      backgroundColor: '#F5E6D3',
      ornaments: ['arch', 'mosque'],
      thickness: 4,
      pattern: 'horseshoe-arch',
    },
  },

  // ════════════════ BADGE (10) ════════════════
  {
    id: 'badge_premium_crescent_emblem', name: 'Crescent Emblem',
    description: 'Crescent moon emblem badge with golden glow.',
    category: 'BADGE', rarity: 'EPIC', price: 1000,
    featured: true, isNew: true, available: true,
    theme: 'ramadan', collectionLabel: 'Premium Badges',
    designKey: 'badge_crescent_emblem', configuration: {
      icon: 'crescent',
      color: '#F5C56A',
      glow: true,
      shape: 'shield',
    },
  },
  {
    id: 'badge_premium_star_medal', name: 'Star Medal',
    description: 'Eight-pointed star medal with rays of light.',
    category: 'BADGE', rarity: 'EPIC', price: 1000, available: true,
    theme: 'geometry', collectionLabel: 'Premium Badges',
    designKey: 'badge_star_medal', configuration: {
      icon: 'star',
      color: '#65C77C',
      glow: true,
      shape: 'medal',
    },
  },
  {
    id: 'badge_premium_muazzin_calligraphy', name: 'Muazzin Calligraphy Badge',
    description: 'Calligraphic badge inspired by classical Muazzin manuscripts.',
    category: 'BADGE', rarity: 'LEGENDARY', price: 1800, available: true,
    theme: 'quran', collectionLabel: 'Premium Badges',
    designKey: 'badge_muazzin_calligraphy', configuration: {
      icon: 'calligraphy',
      color: '#F5C56A',
      glow: true,
      shape: 'octagon',
    },
  },
  {
    id: 'badge_premium_scholar', name: 'Scholar Badge',
    description: 'Badge of scholarly excellence — book and pen motif.',
    category: 'BADGE', rarity: 'RARE', price: 600, available: true,
    theme: 'quran', collectionLabel: 'Premium Badges',
    designKey: 'badge_scholar', configuration: {
      icon: 'book',
      color: '#2E6644',
      glow: false,
      shape: 'circle',
    },
  },
  {
    id: 'badge_premium_mosque_emblem', name: 'Mosque Emblem',
    description: 'Grand mosque silhouette emblem — symbol of devotion.',
    category: 'BADGE', rarity: 'LEGENDARY', price: 1500,
    available: true,
    theme: 'kaaba', collectionLabel: 'Premium Badges',
    designKey: 'badge_mosque_emblem', configuration: {
      icon: 'mosque',
      color: '#F5C56A',
      glow: true,
      shape: 'shield',
    },
  },
  {
    id: 'badge_premium_crescent_gold', name: 'Crescent Gold',
    description: 'Solid gold crescent badge — pure prestige.',
    category: 'BADGE', rarity: 'LEGENDARY', price: 2200,
    limited: true, available: true,
    theme: 'ramadan', collectionLabel: 'Premium Badges',
    designKey: 'badge_crescent_gold', configuration: {
      icon: 'crescent',
      color: '#F59E0B',
      glow: true,
      shape: 'circle',
    },
  },
  {
    id: 'badge_premium_quran_seal', name: 'Quran Seal',
    description: 'The holy Quran in a wax-seal emblem — sacred and refined.',
    category: 'BADGE', rarity: 'MYTHIC', price: 3500,
    limited: true, available: true,
    theme: 'quran', collectionLabel: 'Premium Badges',
    designKey: 'badge_quran_seal', configuration: {
      icon: 'mushaf',
      color: '#65C77C',
      glow: true,
      shape: 'hexagon',
    },
  },
  {
    id: 'badge_premium_geometric_emblem', name: 'Geometric Emblem',
    description: 'Sacred geometry emblem with star and circle motifs.',
    category: 'BADGE', rarity: 'EPIC', price: 1200,
    available: true,
    theme: 'geometry', collectionLabel: 'Premium Badges',
    designKey: 'badge_geometric_emblem', configuration: {
      icon: 'geometric',
      color: '#65C77C',
      glow: true,
      shape: 'octagon',
    },
  },
  {
    id: 'badge_premium_royal_emblem', name: 'Royal Emblem',
    description: 'Royal crest with crown and heritage ornaments.',
    category: 'BADGE', rarity: 'MYTHIC', price: 4000,
    limited: true, available: true,
    theme: 'premium', collectionLabel: 'Premium Badges',
    designKey: 'badge_royal_emblem', configuration: {
      icon: 'crown',
      color: '#F5C56A',
      glow: true,
      shape: 'shield',
    },
  },
  {
    id: 'badge_premium_celestial_medal', name: 'Celestial Medal',
    description: 'A celestial medal with stars and cosmic rays.',
    category: 'BADGE', rarity: 'LEGENDARY', price: 2000,
    available: true,
    theme: 'premium', collectionLabel: 'Premium Badges',
    designKey: 'badge_celestial_medal', configuration: {
      icon: 'celestial',
      color: '#0EA5E9',
      glow: true,
      shape: 'medal',
    },
  },

  // ════════════════ AVATAR (10) ════════════════
  {
    id: 'avatar_premium_crescent_decor', name: 'Crescent Avatar Decor',
    description: 'Avatar overlay with crescent decoration and golden glow.',
    category: 'AVATAR', rarity: 'EPIC', price: 1000,
    featured: true, isNew: true, available: true,
    theme: 'ramadan', collectionLabel: 'Premium Avatar Items',
    designKey: 'avatar_crescent_decor', configuration: {
      overlay: 'crescent',
      color: '#F5C56A',
      accent: '#FFFFFF',
    },
  },
  {
    id: 'avatar_premium_geometric_frame', name: 'Geometric Frame Avatar',
    description: 'Avatar wrapped in geometric star pattern.',
    category: 'AVATAR', rarity: 'EPIC', price: 1100, available: true,
    theme: 'geometry', collectionLabel: 'Premium Avatar Items',
    designKey: 'avatar_geometric_frame', configuration: {
      overlay: 'geometric-star',
      color: '#65C77C',
    },
  },
  {
    id: 'avatar_premium_emerald_glow', name: 'Emerald Glow Avatar',
    description: 'Avatar with emerald radiant glow surrounding it.',
    category: 'AVATAR', rarity: 'EPIC', price: 1200, available: true,
    theme: 'premium', collectionLabel: 'Premium Avatar Items',
    designKey: 'avatar_emerald_glow', configuration: {
      overlay: 'emerald-glow',
      color: '#65C77C',
      glow: true,
    },
  },
  {
    id: 'avatar_premium_golden_halo', name: 'Golden Halo Avatar',
    description: 'Avatar crowned with a golden halo of light.',
    category: 'AVATAR', rarity: 'LEGENDARY', price: 1800,
    available: true,
    theme: 'premium', collectionLabel: 'Premium Avatar Items',
    designKey: 'avatar_golden_halo', configuration: {
      overlay: 'halo',
      color: '#F5C56A',
      glow: true,
    },
  },
  {
    id: 'avatar_premium_arabesque_border', name: 'Arabesque Border Avatar',
    description: 'Avatar adorned with intricate arabesque border.',
    category: 'AVATAR', rarity: 'EPIC', price: 1300, available: true,
    theme: 'geometry', collectionLabel: 'Premium Avatar Items',
    designKey: 'avatar_arabesque_border', configuration: {
      overlay: 'arabesque',
      color: '#F5C56A',
    },
  },
  {
    id: 'avatar_premium_star_sparkle', name: 'Star Sparkle Avatar',
    description: 'Avatar with twinkling stars around it.',
    category: 'AVATAR', rarity: 'RARE', price: 700, available: true,
    theme: 'geometry', collectionLabel: 'Premium Avatar Items',
    designKey: 'avatar_star_sparkle', configuration: {
      overlay: 'stars',
      color: '#F5C56A',
    },
  },
  {
    id: 'avatar_premium_celestial_circle', name: 'Celestial Circle Avatar',
    description: 'Avatar in a celestial cosmic circle.',
    category: 'AVATAR', rarity: 'MYTHIC', price: 3000,
    limited: true, available: true,
    theme: 'premium', collectionLabel: 'Premium Avatar Items',
    designKey: 'avatar_celestial_circle', configuration: {
      overlay: 'celestial',
      color: '#0EA5E9',
      glow: true,
    },
  },
  {
    id: 'avatar_premium_minimal_muslim', name: 'Minimal Muslim Avatar',
    description: 'Clean minimal avatar decoration — elegant simplicity.',
    category: 'AVATAR', rarity: 'COMMON', price: 200, available: true,
    theme: 'geometry', collectionLabel: 'Premium Avatar Items',
    designKey: 'avatar_minimal_muslim', configuration: {
      overlay: 'minimal',
      color: '#2E6644',
    },
  },
  {
    id: 'avatar_premium_royal_crown', name: 'Royal Crown Avatar',
    description: 'Avatar topped with a royal crown ornament.',
    category: 'AVATAR', rarity: 'LEGENDARY', price: 2200,
    available: true,
    theme: 'premium', collectionLabel: 'Premium Avatar Items',
    designKey: 'avatar_royal_crown', configuration: {
      overlay: 'crown',
      color: '#F5C56A',
      glow: true,
    },
  },
  {
    id: 'avatar_premium_mosque_silhouette', name: 'Mosque Silhouette Avatar',
    description: 'Avatar silhouette inside a mosque-shaped frame.',
    category: 'AVATAR', rarity: 'EPIC', price: 1100, available: true,
    theme: 'kaaba', collectionLabel: 'Premium Avatar Items',
    designKey: 'avatar_mosque_silhouette', configuration: {
      overlay: 'mosque',
      color: '#F5C56A',
    },
  },

  // ════════════════ SPECIAL (10) ════════════════
  {
    id: 'special_premium_ramadan_blessing', name: 'Ramadan Blessing',
    description: 'A blessed Ramadan package — frames, backgrounds, name effect, and badge themed for the holy month.',
    category: 'SPECIAL', rarity: 'MYTHIC', price: 18000,
    limited: true, isNew: true, available: true,
    theme: 'ramadan', collectionLabel: 'Premium Special Items',
    designKey: 'special_ramadan_blessing', configuration: {
      bundle: true,
      items: ['frame_premium_ramadan_crescent', 'bg_premium_ramadan_lantern', 'nameeffect_premium_crescent_shimmer', 'badge_premium_crescent_emblem'],
      accent: '#F5C56A',
    },
  },
  {
    id: 'special_premium_eid_celebration_bundle', name: 'Eid Celebration Bundle',
    description: 'Everything you need to celebrate Eid in style — full Eid set.',
    category: 'SPECIAL', rarity: 'MYTHIC', price: 17000,
    limited: true, available: true,
    theme: 'eid_fitr', collectionLabel: 'Premium Special Items',
    designKey: 'special_eid_celebration_bundle', configuration: {
      bundle: true,
      items: ['frame_premium_eid_lantern', 'bg_premium_eid_celebration', 'nameeffect_premium_golden_gradient', 'badge_premium_crescent_gold'],
      accent: '#F59E0B',
    },
  },
  {
    id: 'special_premium_quran_companion', name: 'Quran Companion Bundle',
    description: 'A complete Quran-themed set — frame, background, name effect, and badge for the Quran lover.',
    category: 'SPECIAL', rarity: 'MYTHIC', price: 20000,
    limited: true, available: true,
    theme: 'quran', collectionLabel: 'Premium Special Items',
    designKey: 'special_quran_companion', configuration: {
      bundle: true,
      items: ['frame_premium_golden_arabesque', 'bg_premium_quran_mushaf', 'nameeffect_premium_calligraphic', 'badge_premium_quran_seal'],
      accent: '#65C77C',
    },
  },
  {
    id: 'special_premium_kaaba_pilgrim', name: 'Kaaba Pilgrim Bundle',
    description: 'A set for the devoted pilgrim — Kaaba-themed frame, background, name effect, and badge.',
    category: 'SPECIAL', rarity: 'SPECIAL', price: 50000,
    limited: true, available: true,
    theme: 'kaaba', collectionLabel: 'Premium Special Items',
    designKey: 'special_kaaba_pilgrim', configuration: {
      bundle: true,
      items: ['frame_premium_mosque_arch', 'bg_premium_kaaba_night', 'nameeffect_premium_royal_gold', 'badge_premium_mosque_emblem'],
      accent: '#F5C56A',
    },
  },
  {
    id: 'special_premium_madinah_visitor', name: 'Madinah Visitor Bundle',
    description: 'For those who visited Madinah — emerald-themed set with Green Dome inspiration.',
    category: 'SPECIAL', rarity: 'SPECIAL', price: 45000,
    limited: true, available: true,
    theme: 'madinah', collectionLabel: 'Premium Special Items',
    designKey: 'special_madinah_visitor', configuration: {
      bundle: true,
      items: ['frame_premium_emerald_leaves', 'bg_premium_madinah_green', 'nameeffect_premium_emerald_glow', 'badge_premium_geometric_emblem'],
      accent: '#2E6644',
    },
  },
  {
    id: 'special_premium_hajj_complete', name: 'Hajj Complete Bundle',
    description: 'For those who completed Hajj — premium commemorative set.',
    category: 'SPECIAL', rarity: 'SPECIAL', price: 55000,
    limited: true, available: true,
    theme: 'hajj', collectionLabel: 'Premium Special Items',
    designKey: 'special_hajj_complete', configuration: {
      bundle: true,
      items: ['frame_premium_royal_gold', 'bg_premium_mosque_silhouette', 'nameeffect_premium_royal_gold', 'badge_premium_royal_emblem'],
      accent: '#F5C56A',
    },
  },
  {
    id: 'special_premium_celestial_collection', name: 'Celestial Collection Bundle',
    description: 'A celestial-themed set for those who shine on.',
    category: 'SPECIAL', rarity: 'SPECIAL', price: 40000,
    limited: true, available: true,
    theme: 'premium', collectionLabel: 'Premium Special Items',
    designKey: 'special_celestial_collection', configuration: {
      bundle: true,
      items: ['frame_premium_celestial_circle', 'bg_premium_celestial_stars', 'nameeffect_premium_celestial_dawn', 'badge_premium_celestial_medal'],
      accent: '#0EA5E9',
    },
  },
  {
    id: 'special_premium_royal_emerald_collection', name: 'Royal Emerald Bundle',
    description: 'The Royal Emerald set — crown-level premium Islamic aesthetics.',
    category: 'SPECIAL', rarity: 'SPECIAL', price: 60000,
    limited: true, available: true,
    theme: 'premium', collectionLabel: 'Premium Special Items',
    designKey: 'special_royal_emerald_collection', configuration: {
      bundle: true,
      items: ['frame_premium_royal_gold', 'bg_premium_golden_heritage', 'nameeffect_premium_royal_gold', 'badge_premium_royal_emblem'],
      accent: '#F5C56A',
    },
  },
  {
    id: 'special_premium_geometric_mastery', name: 'Geometric Mastery Bundle',
    description: 'For the geometry lover — Islamic patterns in their finest form.',
    category: 'SPECIAL', rarity: 'SPECIAL', price: 35000,
    limited: true, available: true,
    theme: 'geometry', collectionLabel: 'Premium Special Items',
    designKey: 'special_geometric_mastery', configuration: {
      bundle: true,
      items: ['frame_premium_geometric_star', 'bg_premium_geometric_arabesque', 'nameeffect_premium_star_sparkle', 'badge_premium_geometric_emblem'],
      accent: '#65C77C',
    },
  },
  {
    id: 'special_premium_seeker_trio', name: 'Seeker Trio',
    description: 'Triple-themed bundle for the spiritual seeker — Ramadan, Eid, and Quran.',
    category: 'SPECIAL', rarity: 'MYTHIC', price: 25000,
    isNew: true, available: true,
    theme: 'premium', collectionLabel: 'Premium Special Items',
    designKey: 'special_seeker_trio', configuration: {
      bundle: true,
      items: ['frame_premium_minimal_islamic', 'bg_premium_desert_dunes', 'nameeffect_premium_sacred_glow', 'badge_premium_scholar'],
      accent: '#F5C56A',
    },
  },
];

export const PREMIUM_PRODUCT_COUNT = PREMIUM_PRODUCTS.length;